const DEVICON = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons';
const SIMPLE = 'https://cdn.simpleicons.org';

// [source, path]  — 'devicon' uses DEVICON base, 'simple' uses SIMPLE base
const ICON_MAP = {
  // Languages
  python: ['devicon', 'python/python-original.svg'],
  javascript: ['devicon', 'javascript/javascript-original.svg'],
  typescript: ['devicon', 'typescript/typescript-original.svg'],
  java: ['devicon', 'java/java-original.svg'],
  'c++': ['devicon', 'cplusplus/cplusplus-original.svg'],
  'c#': ['devicon', 'csharp/csharp-original.svg'],
  c: ['devicon', 'c/c-original.svg'],
  go: ['devicon', 'go/go-original.svg'],
  rust: ['devicon', 'rust/rust-plain.svg'],
  ruby: ['devicon', 'ruby/ruby-original.svg'],
  php: ['devicon', 'php/php-original.svg'],
  swift: ['devicon', 'swift/swift-original.svg'],
  kotlin: ['devicon', 'kotlin/kotlin-original.svg'],
  scala: ['devicon', 'scala/scala-original.svg'],
  r: ['devicon', 'r/r-original.svg'],
  dart: ['devicon', 'dart/dart-original.svg'],
  elixir: ['devicon', 'elixir/elixir-original.svg'],
  lua: ['devicon', 'lua/lua-original.svg'],
  perl: ['devicon', 'perl/perl-original.svg'],
  bash: ['devicon', 'bash/bash-original.svg'],
  shell: ['devicon', 'bash/bash-original.svg'],
  powershell: ['devicon', 'powershell/powershell-original.svg'],
  html: ['devicon', 'html5/html5-original.svg'],
  'html5': ['devicon', 'html5/html5-original.svg'],
  css: ['devicon', 'css3/css3-original.svg'],
  'css3': ['devicon', 'css3/css3-original.svg'],
  sql: ['devicon', 'mysql/mysql-original.svg'],
  graphql: ['devicon', 'graphql/graphql-plain.svg'],

  // Frontend
  react: ['devicon', 'react/react-original.svg'],
  'react native': ['devicon', 'react/react-original.svg'],
  'vue.js': ['devicon', 'vuejs/vuejs-original.svg'],
  vuejs: ['devicon', 'vuejs/vuejs-original.svg'],
  vue: ['devicon', 'vuejs/vuejs-original.svg'],
  'angular': ['devicon', 'angularjs/angularjs-original.svg'],
  'next.js': ['devicon', 'nextjs/nextjs-original.svg'],
  nextjs: ['devicon', 'nextjs/nextjs-original.svg'],
  'nuxt.js': ['devicon', 'nuxtjs/nuxtjs-original.svg'],
  nuxtjs: ['devicon', 'nuxtjs/nuxtjs-original.svg'],
  svelte: ['devicon', 'svelte/svelte-original.svg'],
  tailwindcss: ['devicon', 'tailwindcss/tailwindcss-plain.svg'],
  tailwind: ['devicon', 'tailwindcss/tailwindcss-plain.svg'],
  bootstrap: ['devicon', 'bootstrap/bootstrap-original.svg'],
  sass: ['devicon', 'sass/sass-original.svg'],
  scss: ['devicon', 'sass/sass-original.svg'],
  vite: ['devicon', 'vitejs/vitejs-original.svg'],
  webpack: ['devicon', 'webpack/webpack-original.svg'],
  'three.js': ['simple', 'threedotjs'],
  threejs: ['simple', 'threedotjs'],
  'framer motion': ['simple', 'framer'],
  framer: ['simple', 'framer'],
  redux: ['devicon', 'redux/redux-original.svg'],

  // Backend
  'node.js': ['devicon', 'nodejs/nodejs-original.svg'],
  nodejs: ['devicon', 'nodejs/nodejs-original.svg'],
  node: ['devicon', 'nodejs/nodejs-original.svg'],
  express: ['devicon', 'express/express-original.svg'],
  'express.js': ['devicon', 'express/express-original.svg'],
  fastapi: ['devicon', 'fastapi/fastapi-original.svg'],
  flask: ['devicon', 'flask/flask-original.svg'],
  django: ['devicon', 'django/django-plain.svg'],
  spring: ['devicon', 'spring/spring-original.svg'],
  'spring boot': ['devicon', 'spring/spring-original.svg'],
  laravel: ['devicon', 'laravel/laravel-plain.svg'],
  rails: ['devicon', 'rails/rails-original-wordmark.svg'],
  'ruby on rails': ['devicon', 'rails/rails-original-wordmark.svg'],
  nestjs: ['devicon', 'nestjs/nestjs-plain.svg'],
  'nest.js': ['devicon', 'nestjs/nestjs-plain.svg'],
  graphene: ['simple', 'graphql'],
  nginx: ['devicon', 'nginx/nginx-original.svg'],
  apache: ['devicon', 'apache/apache-original.svg'],

  // Databases
  postgresql: ['devicon', 'postgresql/postgresql-original.svg'],
  postgres: ['devicon', 'postgresql/postgresql-original.svg'],
  mysql: ['devicon', 'mysql/mysql-original.svg'],
  mongodb: ['devicon', 'mongodb/mongodb-original.svg'],
  redis: ['devicon', 'redis/redis-original.svg'],
  sqlite: ['devicon', 'sqlite/sqlite-original.svg'],
  firebase: ['devicon', 'firebase/firebase-plain.svg'],
  supabase: ['simple', 'supabase'],
  cassandra: ['devicon', 'cassandra/cassandra-original.svg'],
  elasticsearch: ['devicon', 'elasticsearch/elasticsearch-original.svg'],
  neo4j: ['devicon', 'neo4j/neo4j-original.svg'],
  dynamodb: ['simple', 'amazondynamodb'],
  'amazon dynamodb': ['simple', 'amazondynamodb'],

  // Cloud & DevOps
  aws: ['devicon', 'amazonwebservices/amazonwebservices-original.svg'],
  'amazon web services': ['devicon', 'amazonwebservices/amazonwebservices-original.svg'],
  gcp: ['devicon', 'googlecloud/googlecloud-original.svg'],
  'google cloud': ['devicon', 'googlecloud/googlecloud-original.svg'],
  azure: ['devicon', 'azure/azure-original.svg'],
  docker: ['devicon', 'docker/docker-original.svg'],
  kubernetes: ['devicon', 'kubernetes/kubernetes-plain.svg'],
  k8s: ['devicon', 'kubernetes/kubernetes-plain.svg'],
  terraform: ['devicon', 'terraform/terraform-original.svg'],
  ansible: ['devicon', 'ansible/ansible-original.svg'],
  jenkins: ['devicon', 'jenkins/jenkins-original.svg'],
  'github actions': ['simple', 'githubactions'],
  'ci/cd': ['simple', 'githubactions'],
  vercel: ['devicon', 'vercel/vercel-original.svg'],
  netlify: ['devicon', 'netlify/netlify-original.svg'],
  heroku: ['devicon', 'heroku/heroku-original.svg'],
  'digital ocean': ['devicon', 'digitalocean/digitalocean-original.svg'],
  digitalocean: ['devicon', 'digitalocean/digitalocean-original.svg'],
  cloudflare: ['simple', 'cloudflare'],
  linux: ['devicon', 'linux/linux-original.svg'],
  ubuntu: ['devicon', 'ubuntu/ubuntu-plain.svg'],

  // AI / ML
  pytorch: ['devicon', 'pytorch/pytorch-original.svg'],
  tensorflow: ['devicon', 'tensorflow/tensorflow-original.svg'],
  keras: ['devicon', 'keras/keras-original.svg'],
  'scikit-learn': ['simple', 'scikitlearn'],
  scikitlearn: ['simple', 'scikitlearn'],
  pandas: ['devicon', 'pandas/pandas-original.svg'],
  numpy: ['devicon', 'numpy/numpy-original.svg'],
  matplotlib: ['simple', 'matplotlib'],
  opencv: ['devicon', 'opencv/opencv-original.svg'],
  openai: ['simple', 'openai'],
  langchain: ['simple', 'langchain'],
  huggingface: ['simple', 'huggingface'],
  'hugging face': ['simple', 'huggingface'],
  streamlit: ['simple', 'streamlit'],
  jupyter: ['devicon', 'jupyter/jupyter-original.svg'],

  // Tools
  git: ['devicon', 'git/git-original.svg'],
  github: ['devicon', 'github/github-original.svg'],
  gitlab: ['devicon', 'gitlab/gitlab-original.svg'],
  bitbucket: ['devicon', 'bitbucket/bitbucket-original.svg'],
  figma: ['devicon', 'figma/figma-original.svg'],
  jira: ['devicon', 'jira/jira-original.svg'],
  confluence: ['devicon', 'confluence/confluence-original.svg'],
  slack: ['simple', 'slack'],
  postman: ['simple', 'postman'],
  vscode: ['devicon', 'vscode/vscode-original.svg'],
  'vs code': ['devicon', 'vscode/vscode-original.svg'],
  vim: ['devicon', 'vim/vim-original.svg'],
  xcode: ['devicon', 'xcode/xcode-original.svg'],
  'android studio': ['devicon', 'androidstudio/androidstudio-original.svg'],
  npm: ['devicon', 'npm/npm-original-wordmark.svg'],
  yarn: ['devicon', 'yarn/yarn-original.svg'],
  pnpm: ['simple', 'pnpm'],
  storybook: ['devicon', 'storybook/storybook-original.svg'],
  jest: ['devicon', 'jest/jest-plain.svg'],
  cypress: ['simple', 'cypress'],
  playwright: ['simple', 'playwright'],
  eslint: ['devicon', 'eslint/eslint-original.svg'],
  prettier: ['simple', 'prettier'],
  'socket.io': ['simple', 'socketdotio'],
  socketio: ['simple', 'socketdotio'],
  prisma: ['simple', 'prisma'],
  'drizzle': ['simple', 'drizzle'],
  trpc: ['simple', 'trpc'],
  'rest api': ['simple', 'fastapi'],
  restapi: ['simple', 'fastapi'],
};

export function getSkillIcon(name) {
  if (!name) return null;
  const key = name.toLowerCase().trim();
  const entry = ICON_MAP[key];
  if (!entry) return null;
  return entry[0] === 'devicon'
    ? `${DEVICON}/${entry[1]}`
    : `${SIMPLE}/${entry[1]}`;
}
